## Module for building Henderson's Mixed Model Equations for single trait



### Data set to test the module

In [1]:
using DataFrames

In [2]:
FILE = "../../data/small.ped";

In [3]:
B = ["S1","D1","O1","O3"]
Animal = repeat(B,inner=[3])
Age = repmat([1,2,3],4)
intercept = ones(12,1)
df = DataFrame(Animal=Animal,Age=Age,y=randn(12));

In [4]:
df

12x3 DataFrames.DataFrame
| Row | Animal | Age | y         |
|-----|--------|-----|-----------|
| 1   | "S1"   | 1   | 1.2651    |
| 2   | "S1"   | 2   | -0.134525 |
| 3   | "S1"   | 3   | -0.25645  |
| 4   | "D1"   | 1   | -1.12096  |
| 5   | "D1"   | 2   | -0.102537 |
| 6   | "D1"   | 3   | -0.981314 |
| 7   | "O1"   | 1   | -0.349881 |
| 8   | "O1"   | 2   | 0.462861  |
| 9   | "O1"   | 3   | -1.09094  |
| 10  | "O3"   | 1   | -0.214849 |
| 11  | "O3"   | 2   | 1.3569    |
| 12  | "O3"   | 3   | 1.11415   |

### <font color="red"> Run module</font>

In [5]:
MODULE_PATH="/Users/rohan/Box Sync/GitHub/JuliaClassReview/Module/MME.jl";

In [6]:
include(MODULE_PATH)

MMEModule

In [7]:
ped = PedModule.mkPed(FILE);

In [8]:
varRes=1.0
mme = MMEModule.initMME("y = intercept + Age + Animal",varRes)
#MMEModule.covList(mme,"Age")
G=zeros(1,1)
G[1,1]=1.0
MMEModule.setAsRandom(mme,"Animal",ped,G)
#MMEModule.setAsRandom(mme,"Age",2.0)


resG = MMEModule.getSolG(mme,df);

10 

In [9]:
resG

9x2 Array{Any,2}:
 "intercept: intercept"  -0.095642  
 "Age: 1"                -0.100777  
 "Age: 2"                 0.400045  
 "Age: 3"                -0.299268  
 "Animal: S1"             0.383276  
 "Animal: D1"            -0.386528  
 "Animal: O1"            -0.138858  
 "Animal: O3"             0.507975  
 "Animal: O2"            -0.00162569

0.0005715250083931588
20 6.560989302176208e-5
30 7.531880184177994e-6
40 8.646442860376982e-7


In [11]:
out=MMEModule.sampleMCMC(5000,mme,df;outFreq=100);

at sample: 100
at sample: 200
at sample: 300
at sample: 400
at sample: 500
at sample: 600
at sample: 700
at sample: 800
at sample: 900
at sample: 1000
at sample: 1100
at sample: 1200
at sample: 1300
at sample: 1400
at sample: 1500
at sample: 1600
at sample: 1700
at sample: 1800
at sample: 1900
at sample: 2000
at sample: 2100
at sample: 2200
at sample: 2300
at sample: 2400
at sample: 2500
at sample: 2600
at sample: 2700
at sample: 2800
at sample: 2900
at sample: 3000
at sample: 3100
at sample: 3200
at sample: 3300
at sample: 3400
at sample: 3500
at sample: 3600
at sample: 3700
at sample: 3800
at sample: 3900
at sample: 4000
at sample: 4100
at sample: 4200
at sample: 4300
at sample: 4400
at sample: 4500
at sample: 4600
at sample: 4700
at sample: 4800
at sample: 4900
at sample: 5000


In [14]:
keys(out)

Base.KeyIterator for a Dict{Any,Any} with 1 entry. Keys:
  "posteriorMeanLocationParms"

In [15]:
out["posteriorMeanLocationParms"]

9x2 Array{Any,2}:
 "intercept: intercept"  -16.3066   
 "Age: 1"                 16.1841   
 "Age: 2"                 16.6841   
 "Age: 3"                 15.9773   
 "Animal: S1"              0.285753 
 "Animal: D1"             -0.35989  
 "Animal: O1"             -0.158023 
 "Animal: O3"              0.331024 
 "Animal: O2"             -0.0464399

In [16]:
resG

9x2 Array{Any,2}:
 "intercept: intercept"  -0.095642  
 "Age: 1"                -0.100777  
 "Age: 2"                 0.400045  
 "Age: 3"                -0.299268  
 "Animal: S1"             0.383276  
 "Animal: D1"            -0.386528  
 "Animal: O1"            -0.138858  
 "Animal: O3"             0.507975  
 "Animal: O2"            -0.00162569

In [17]:
;pwd

/Users/rohan/Box Sync/GitHub/JuliaClassReview/notes/singeTrait
