## Module for building Henderson's Mixed Model Equations for single trait



### Data set to test the module

In [1]:
using DataFrames

In [2]:
FILE = "../../data/small.ped";

In [3]:
B = ["S1","D1","O1","O3"]
Animal = repeat(B,inner=[3])
Age = repmat([1,2,3],4)
intercept = ones(12,1)
df = DataFrame(Animal=Animal,Age=Age,y=randn(12));

In [4]:
df

12x3 DataFrames.DataFrame
| Row | Animal | Age | y         |
|-----|--------|-----|-----------|
| 1   | "S1"   | 1   | -0.855173 |
| 2   | "S1"   | 2   | -0.163337 |
| 3   | "S1"   | 3   | 0.426724  |
| 4   | "D1"   | 1   | 2.02107   |
| 5   | "D1"   | 2   | 0.76379   |
| 6   | "D1"   | 3   | -0.362567 |
| 7   | "O1"   | 1   | -0.735332 |
| 8   | "O1"   | 2   | 0.228232  |
| 9   | "O1"   | 3   | -0.43392  |
| 10  | "O3"   | 1   | -0.266107 |
| 11  | "O3"   | 2   | -1.7626   |
| 12  | "O3"   | 3   | -0.906304 |

### <font color="red"> Run module</font>

In [5]:
MODULE_PATH="/Users/rohan/Box Sync/GitHub/JuliaClassReview/Module/MME.jl";

In [6]:
include(MODULE_PATH)

MMEModule

In [7]:
ped = PedModule.mkPed(FILE);

In [8]:
varRes=1.0
mme = MMEModule.initMME("y = intercept + Age + Animal",varRes)
#MMEModule.covList(mme,"Age")
G=zeros(1,1)
G[1,1]=1.0
#MMEModule.setAsRandom(mme,"Animal",ped,G)
MMEModule.setAsRandom(mme,"Age",2.0,4.1)
MMEModule.outputSamplesFor(mme,"Age")
resG = MMEModule.getSolG(mme,df);

In [9]:
resG

8x2 Array{Any,2}:
 "intercept: intercept"  -0.17046  
 "Age: 1"                 0.188067 
 "Age: 2"                -0.0560167
 "Age: 3"                -0.13205  
 "Animal: S1"            -0.0268021
 "Animal: D1"             0.977892 
 "Animal: O1"            -0.143213 
 "Animal: O3"            -0.807877 

In [10]:
map(Float64,resG[:,2])

8-element Array{Float64,1}:
 -0.17046  
  0.188067 
 -0.0560167
 -0.13205  
 -0.0268021
  0.977892 
 -0.143213 
 -0.807877 

In [11]:
out=MMEModule.sampleMCMC(50,mme,df;sol=map(Float64,resG[:,2]),outFreq=10);

at sample: 10

In [12]:
out=MMEModule.sampleMCMC(50,mme,df;outFreq=10);

In [13]:
keys(out)

Base.KeyIterator for a Dict{Any,Any} with 4 entries. Keys:
  "posteriorMeanLocationParms"
  "MCMCSamples for variance of :Age"
  "MCMCSamples: Age"
  "MCMCSamples for residual variance"


at sample: 20
at sample: 30
at sample: 40
at sample: 50
at sample: 10
at sample: 20
at sample: 30
at sample: 40
at sample: 50


In [14]:
out["posteriorMeanLocationParms"]

8x2 Array{Any,2}:
 "intercept: intercept"   1.83659  
 "Age: 1"                -0.0858167
 "Age: 2"                -0.26129  
 "Age: 3"                -0.350971 
 "Animal: S1"            -1.80265  
 "Animal: D1"            -0.841662 
 "Animal: O1"            -2.00819  
 "Animal: O3"            -2.62895  

In [15]:
out["MCMCSamples for variance of :Age"]

50-element Array{Float64,1}:
 1.15749 
 0.900257
 0.484604
 0.2966  
 1.49342 
 0.365354
 1.72581 
 0.434278
 1.09184 
 1.16339 
 0.459322
 1.18546 
 0.98179 
 ⋮       
 0.870902
 0.478204
 0.966719
 0.65049 
 0.716197
 0.749995
 1.08636 
 0.548541
 0.947735
 1.07847 
 0.475687
 0.572814

In [16]:
out["MCMCSamples: Age"]

50x3 Array{Float64,2}:
  0.65562     0.276866    0.396184 
  0.61604     0.0316518  -0.648451 
  0.558011    0.0940989  -0.153667 
  0.351658   -0.202818   -0.0377727
 -0.165797   -0.746234   -0.209785 
  0.512071   -0.0572499  -0.645098 
 -0.597531   -0.281893   -0.193454 
 -0.833136   -0.502713   -0.981447 
 -0.885709   -0.646847   -0.538482 
 -0.404267   -0.915583   -0.943707 
 -0.984735   -0.0432628  -0.152714 
 -0.435422    0.464573    0.10425  
  0.444343   -0.464618    0.460967 
  ⋮                                
 -0.140946   -0.927591   -0.357467 
  0.283278    0.748543    0.180069 
  0.0677969   0.459881   -0.0889523
  0.35098     0.96397     0.104478 
 -0.211242   -0.279926   -0.247192 
 -0.282649   -0.462912   -0.772977 
  0.114476   -0.451515   -0.680299 
 -0.233252   -0.8426     -0.564217 
 -0.856115   -0.310405   -0.241892 
 -0.506417   -0.753806   -0.58576  
 -0.668068   -1.123      -0.80177  
 -1.00496    -0.671062   -0.235843 

In [17]:
out["MCMCSamples for residual variance"]

50-element Array{Float64,1}:
 0.601765
 0.997421
 0.993911
 0.309113
 0.273613
 1.55131 
 0.558691
 1.00562 
 0.539487
 0.628775
 0.734407
 1.82099 
 1.17205 
 ⋮       
 0.825574
 0.462908
 0.44913 
 0.683276
 1.15244 
 0.557909
 0.916812
 0.492773
 0.687222
 0.919362
 1.25495 
 1.26706 