## Module for building Henderson's Mixed Model Equations for single trait



### Data set to test the module

In [1]:
using DataFrames

In [2]:
FILE = "../../data/small.ped";

In [3]:
B = ["S1","D1","O1","O3"]
Animal = repeat(B,inner=[3])
Age = repmat([1,2,3],4)
intercept = ones(12,1)
df = DataFrame(Animal=Animal,Age=Age,y=randn(12));

In [4]:
df

12x3 DataFrames.DataFrame
| Row | Animal | Age | y         |
|-----|--------|-----|-----------|
| 1   | "S1"   | 1   | 0.0868066 |
| 2   | "S1"   | 2   | 0.376239  |
| 3   | "S1"   | 3   | 0.0238586 |
| 4   | "D1"   | 1   | -0.984896 |
| 5   | "D1"   | 2   | 0.0970292 |
| 6   | "D1"   | 3   | 0.284703  |
| 7   | "O1"   | 1   | 0.219092  |
| 8   | "O1"   | 2   | -0.335379 |
| 9   | "O1"   | 3   | -0.788749 |
| 10  | "O3"   | 1   | -0.279377 |
| 11  | "O3"   | 2   | 0.455353  |
| 12  | "O3"   | 3   | 0.0864787 |

### <font color="red"> Run module</font>

In [5]:
MODULE_PATH="/Users/rohan/Box Sync/GitHub/JuliaClassReview/Module/MME.jl";

In [6]:
include(MODULE_PATH)

MMEModule

In [7]:
ped = PedModule.mkPed(FILE);

In [8]:
varRes=1.0
mme = MMEModule.initMME("y = intercept + Age + Animal",varRes)
#MMEModule.covList(mme,"Age")
G=zeros(1,1)
G[1,1]=1.0
MMEModule.setAsRandom(mme,"Animal",ped,G)
#MMEModule.setAsRandom(mme,"Age",2.0)
MMEModule.outputSamplesFor(mme,"Age")
resG = MMEModule.getSolG(mme,df);

10 

In [9]:
resG

9x2 Array{Any,2}:
 "intercept: intercept"  -0.0463104 
 "Age: 1"                -0.176357  
 "Age: 2"                 0.211547  
 "Age: 3"                -0.0351904 
 "Animal: S1"             0.13782   
 "Animal: D1"            -0.134627  
 "Animal: O1"            -0.152582  
 "Animal: O3"             0.0809157 
 "Animal: O2"             0.00159669

3.0566606276994856e-6


In [10]:
out=MMEModule.sampleMCMC(50,mme,df;outFreq=100);

In [11]:
keys(out)

Base.KeyIterator for a Dict{Any,Any} with 2 entries. Keys:
  "posteriorMeanLocationParms"
  "MCMCSamples:Age"

In [12]:
out["posteriorMeanLocationParms"]

9x2 Array{Any,2}:
 "intercept: intercept"  -3.97201  
 "Age: 1"                 4.14483  
 "Age: 2"                 4.36375  
 "Age: 3"                 4.20799  
 "Animal: S1"            -0.0878882
 "Animal: D1"            -0.410166 
 "Animal: O1"            -0.357201 
 "Animal: O3"            -0.210072 
 "Animal: O2"            -0.223836 

In [14]:
out["MCMCSamples:Age"]

50x3 Array{Float64,2}:
 0.439251   0.791496  0.159025
 0.0336728  0.58044   0.678969
 0.196471   1.47693   0.406587
 1.82902    1.69327   1.79758 
 1.39313    1.4208    0.827657
 1.7182     2.53868   2.49058 
 2.817      2.69487   3.04941 
 3.45379    3.36858   2.82498 
 3.98659    2.88343   3.25669 
 3.39892    4.16247   3.10305 
 3.68015    4.00826   3.22992 
 3.21445    3.39603   3.56488 
 4.4701     3.91131   3.102   
 ⋮                            
 5.304      6.37513   6.55381 
 5.6544     5.74031   5.26745 
 6.95065    5.52262   5.8012  
 4.55517    6.44239   5.86558 
 4.70624    5.68129   5.79154 
 4.25926    5.278     6.38829 
 3.40337    5.09261   5.71291 
 4.54438    4.50552   5.64562 
 4.68639    4.38129   4.22588 
 4.80793    4.74678   4.23147 
 4.96966    4.26141   4.313   
 4.68444    5.15429   5.39207 