## Module for building Henderson's Mixed Model Equations for single trait



### Data set to test the module

In [1]:
using DataFrames

In [2]:
FILE = "../../data/small.ped";

In [3]:
B = ["S1","D1","O1","O3"]
Animal = repeat(B,inner=[3])
Age = repmat([1,2,3],4)
intercept = ones(12,1)
df = DataFrame(Animal=Animal,Age=Age,y=randn(12));

In [4]:
df

12x3 DataFrames.DataFrame
| Row | Animal | Age | y         |
|-----|--------|-----|-----------|
| 1   | "S1"   | 1   | -1.11393  |
| 2   | "S1"   | 2   | 0.892033  |
| 3   | "S1"   | 3   | 0.474514  |
| 4   | "D1"   | 1   | -0.863287 |
| 5   | "D1"   | 2   | 0.957823  |
| 6   | "D1"   | 3   | 1.61524   |
| 7   | "O1"   | 1   | -1.412    |
| 8   | "O1"   | 2   | 0.0199339 |
| 9   | "O1"   | 3   | 1.35281   |
| 10  | "O3"   | 1   | 1.4804    |
| 11  | "O3"   | 2   | -1.59124  |
| 12  | "O3"   | 3   | 1.08334   |

### <font color="red"> Run module</font>

In [5]:
MODULE_PATH="/Users/rohan/Box Sync/GitHub/JuliaClassReview/Module/MME.jl";

In [6]:
include(MODULE_PATH)

MMEModule

In [7]:
ped = PedModule.mkPed(FILE);

In [8]:
varRes=1.0
mme = MMEModule.initMME("y = intercept + Age + Animal",varRes)
#MMEModule.covList(mme,"Age")
G=zeros(1,1)
G[1,1]=1.0
#MMEModule.setAsRandom(mme,"Animal",ped,G)
MMEModule.setAsRandom(mme,"Age",2.0,4.1)
MMEModule.outputSamplesFor(mme,"Age")
resG = MMEModule.getSolG(mme,df);

In [9]:
resG

8x2 Array{Any,2}:
 "intercept: intercept"   0.241303 
 "Age: 1"                -0.638671 
 "Age: 2"                -0.152593 
 "Age: 3"                 0.791264 
 "Animal: S1"            -0.157097 
 "Animal: D1"             0.328623 
 "Animal: O1"            -0.254389 
 "Animal: O3"             0.0828628

In [10]:
out=MMEModule.sampleMCMC(50,mme,df;outFreq=100);

In [11]:
keys(out)

Base.KeyIterator for a Dict{Any,Any} with 3 entries. Keys:
  "posteriorMeanLocationParms"
  "MCMCSamples for variance of :Age"
  "MCMCSamples: Age"

In [12]:
out["posteriorMeanLocationParms"]

8x2 Array{Any,2}:
 "intercept: intercept"   1.74906 
 "Age: 1"                -0.616912
 "Age: 2"                -0.276071
 "Age: 3"                 0.400068
 "Animal: S1"            -1.48778 
 "Animal: D1"            -0.969426
 "Animal: O1"            -1.75657 
 "Animal: O3"            -1.36537 

In [13]:
out["MCMCSamples for variance of :Age"]

50-element Array{Float64,1}:
 0.57635 
 2.50191 
 1.87681 
 5.82442 
 2.72949 
 1.55806 
 0.673352
 0.519531
 2.74868 
 3.13455 
 0.567265
 0.368057
 1.66176 
 ⋮       
 0.828393
 0.297028
 0.657517
 1.75573 
 0.593864
 0.603328
 2.34293 
 1.634   
 2.87826 
 1.34156 
 0.408313
 0.50757 

In [14]:
out["MCMCSamples: Age"]

50x3 Array{Float64,2}:
 -1.25882    -0.483841    0.326881
 -1.26864    -0.965017   -0.363589
 -1.08045    -1.54588     0.648129
 -1.18498    -1.41351     0.38695 
 -2.11691    -0.52798    -0.126097
 -1.56192    -0.650937    0.167915
 -1.31019     0.243411   -1.30151 
 -1.38007    -0.162984   -0.213353
  0.127005   -0.590514   -0.104341
 -1.0308     -0.794462    0.654387
 -0.789366   -1.27971     0.256524
 -0.570009   -0.43605    -0.292536
  0.0443453  -0.513847    0.115113
  ⋮                               
 -0.0493915   0.0982248   1.00103 
  0.178197    0.0994745   1.00511 
 -0.0311005   0.156316    0.46877 
 -0.275749    0.651183    0.653128
 -0.607804   -0.693453    0.408333
 -0.669066   -0.182866    0.159792
 -0.330929   -0.22934     0.698387
 -0.292638    0.444838    1.3967  
  0.307164    0.300982    0.859142
 -0.819236    0.29074     0.980576
  0.316579   -0.202487    0.667663
 -0.512586    0.0950273   0.531486