## Tools for building Henderson's Mixed Model Equations

Here we will see how the mixed model equations (HMME) can be built given a data set and a model string. 


In [1]:
include ("../../PedModule.jl/src/PedModule.jl")
using DataFrames

In [2]:
df = readtable("MTData", separator = ' ')

4x4 DataFrame
| Row | y1  | y2  | y3  | trt |
|-----|-----|-----|-----|-----|
| 1   | 1.0 | 2.0 | 1.2 | 1   |
| 2   | 1.1 | NA  | 3.1 | 1   |
| 3   | 0.9 | 1.9 | NA  | 2   |
| 4   | 1.2 | 1.7 | 1.9 | 2   |

In [3]:
tstMsng = [!isna(df[:y1]) !isna(df[:y2]) !isna(df[:y3])]

4x3 BitArray{2}:
 true   true   true
 true  false   true
 true   true  false
 true   true   true

In [4]:
convert(Array, df[:y1], 0)

4-element Array{Float64,1}:
 1.0
 1.1
 0.9
 1.2

In [5]:
X1 = [
    1 0
    1 0
    0 1
    0 1
]

4x2 Array{Int64,2}:
 1  0
 1  0
 0  1
 0  1

In [6]:
X2 = [
    1 0
    0 1
    0 1
]

3x2 Array{Int64,2}:
 1  0
 0  1
 0  1

In [7]:
X = [
    X1 zeros(4,2)
    zeros(3,2) X2
]

7x4 Array{Float64,2}:
 1.0  0.0  0.0  0.0
 1.0  0.0  0.0  0.0
 0.0  1.0  0.0  0.0
 0.0  1.0  0.0  0.0
 0.0  0.0  1.0  0.0
 0.0  0.0  0.0  1.0
 0.0  0.0  0.0  1.0

In [8]:
sel = [!isna(df[:y1]),  !isna(df[:y2])]

8-element BitArray{1}:
  true
  true
  true
  true
  true
 false
  true
  true

In [9]:
R0 = [1 0.5
      0.5 2.0]
R  = kron(R0,eye(4))

8x8 Array{Float64,2}:
 1.0  0.0  0.0  0.0  0.5  0.0  0.0  0.0
 0.0  1.0  0.0  0.0  0.0  0.5  0.0  0.0
 0.0  0.0  1.0  0.0  0.0  0.0  0.5  0.0
 0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.5
 0.5  0.0  0.0  0.0  2.0  0.0  0.0  0.0
 0.0  0.5  0.0  0.0  0.0  2.0  0.0  0.0
 0.0  0.0  0.5  0.0  0.0  0.0  2.0  0.0
 0.0  0.0  0.0  0.5  0.0  0.0  0.0  2.0

In [10]:
Ri = inv(R)
round(Ri,3)

8x8 Array{Float64,2}:
  1.143   0.0     0.0     0.0    -0.286   0.0     0.0    -0.0  
  0.0     1.143   0.0     0.0     0.0    -0.286   0.0    -0.0  
  0.0     0.0     1.143   0.0     0.0     0.0    -0.286  -0.0  
  0.0     0.0     0.0     1.143   0.0     0.0     0.0    -0.286
 -0.286   0.0     0.0     0.0     0.571   0.0     0.0    -0.0  
  0.0    -0.286   0.0     0.0     0.0     0.571   0.0    -0.0  
  0.0     0.0    -0.286   0.0     0.0     0.0     0.571  -0.0  
  0.0     0.0     0.0    -0.286   0.0     0.0     0.0     0.571

In [11]:
round(kron(inv(R0),eye(4)),3)

8x8 Array{Float64,2}:
  1.143   0.0     0.0     0.0    -0.286  -0.0    -0.0    -0.0  
  0.0     1.143   0.0     0.0    -0.0    -0.286  -0.0    -0.0  
  0.0     0.0     1.143   0.0    -0.0    -0.0    -0.286  -0.0  
  0.0     0.0     0.0     1.143  -0.0    -0.0    -0.0    -0.286
 -0.286  -0.0    -0.0    -0.0     0.571   0.0     0.0     0.0  
 -0.0    -0.286  -0.0    -0.0     0.0     0.571   0.0     0.0  
 -0.0    -0.0    -0.286  -0.0     0.0     0.0     0.571   0.0  
 -0.0    -0.0    -0.0    -0.286   0.0     0.0     0.0     0.571

In [12]:
sel

8-element BitArray{1}:
  true
  true
  true
  true
  true
 false
  true
  true

In [13]:
R = R[sel,sel]

7x7 Array{Float64,2}:
 1.0  0.0  0.0  0.0  0.5  0.0  0.0
 0.0  1.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  1.0  0.0  0.0  0.5  0.0
 0.0  0.0  0.0  1.0  0.0  0.0  0.5
 0.5  0.0  0.0  0.0  2.0  0.0  0.0
 0.0  0.0  0.5  0.0  0.0  2.0  0.0
 0.0  0.0  0.0  0.5  0.0  0.0  2.0

In [14]:
Ri = inv(R)
round(Ri,3)

7x7 Array{Float64,2}:
  1.143  0.0   0.0     0.0    -0.286   0.0    -0.0  
  0.0    1.0   0.0     0.0     0.0     0.0    -0.0  
  0.0    0.0   1.143   0.0     0.0    -0.286  -0.0  
  0.0    0.0   0.0     1.143   0.0     0.0    -0.286
 -0.286  0.0   0.0     0.0     0.571   0.0    -0.0  
  0.0    0.0  -0.286   0.0     0.0     0.571  -0.0  
  0.0    0.0   0.0    -0.286   0.0     0.0     0.571

In [15]:
round(X'Ri*X,3)

4x4 Array{Float64,2}:
  2.143   0.0    -0.286   0.0  
  0.0     2.286   0.0    -0.571
 -0.286   0.0     0.571   0.0  
  0.0    -0.571   0.0     1.143

In [16]:
X = [
    X1          zeros(4,2)
    zeros(4,2)  X1
    ]    

8x4 Array{Float64,2}:
 1.0  0.0  0.0  0.0
 1.0  0.0  0.0  0.0
 0.0  1.0  0.0  0.0
 0.0  1.0  0.0  0.0
 0.0  0.0  1.0  0.0
 0.0  0.0  1.0  0.0
 0.0  0.0  0.0  1.0
 0.0  0.0  0.0  1.0

In [17]:
Ri = round(kron(inv(R0),eye(4)),3)
Ri[2,:] = 0
Ri[:,2] = 0
Ri[2,2] = 1.0
Ri[6,6] = 0
round(Ri,3)

8x8 Array{Float64,2}:
  1.143  0.0   0.0     0.0    -0.286  -0.0  -0.0    -0.0  
  0.0    1.0   0.0     0.0     0.0     0.0   0.0     0.0  
  0.0    0.0   1.143   0.0    -0.0    -0.0  -0.286  -0.0  
  0.0    0.0   0.0     1.143  -0.0    -0.0  -0.0    -0.286
 -0.286  0.0  -0.0    -0.0     0.571   0.0   0.0     0.0  
 -0.0    0.0  -0.0    -0.0     0.0     0.0   0.0     0.0  
 -0.0    0.0  -0.286  -0.0     0.0     0.0   0.571   0.0  
 -0.0    0.0  -0.0    -0.286   0.0     0.0   0.0     0.571

In [18]:
X'Ri*X

4x4 Array{Float64,2}:
  2.143   0.0    -0.286   0.0  
  0.0     2.286   0.0    -0.572
 -0.286   0.0     0.571   0.0  
  0.0    -0.572   0.0     1.142

In [19]:
R0=[
    1.0 0.5 0.5
    0.5 2.0 0.5
    0.5 0.5 4.0
]

3x3 Array{Float64,2}:
 1.0  0.5  0.5
 0.5  2.0  0.5
 0.5  0.5  4.0

In [20]:
sel = bool([1,1,1])
RZ = zeros(3,3)
RZ[sel,sel]=inv(R0[sel,sel])
RZ

3x3 Array{Float64,2}:
  1.19231   -0.269231   -0.115385 
 -0.269231   0.576923   -0.0384615
 -0.115385  -0.0384615   0.269231 

In [21]:
sel = bool([1,1,0])
RZ = zeros(3,3)
RZ[sel,sel]=inv(R0[sel,sel])
RZ

3x3 Array{Float64,2}:
  1.14286   -0.285714  0.0
 -0.285714   0.571429  0.0
  0.0        0.0       0.0

In [22]:
sel = bool([0,1,1])
RZ = zeros(3,3)
RZ[sel,sel]=inv(R0[sel,sel])
RZ

3x3 Array{Float64,2}:
 0.0   0.0         0.0      
 0.0   0.516129   -0.0645161
 0.0  -0.0645161   0.258065 

In [23]:
sel = bool([0,1,1])
RZ = zeros(3,3)
RZ[sel,sel]=inv(R0[sel,sel])
RZ

3x3 Array{Float64,2}:
 0.0   0.0         0.0      
 0.0   0.516129   -0.0645161
 0.0  -0.0645161   0.258065 

In [24]:
sel = bool([1,0,1])
RZ = zeros(3,3)
RZ[sel,sel]=inv(R0[sel,sel])
RZ

3x3 Array{Float64,2}:
  1.06667   0.0  -0.133333
  0.0       0.0   0.0     
 -0.133333  0.0   0.266667

In [25]:
type ResVar
    R0::Array{Float64,2}
    RiDict::Dict{BitArray{1},Array{Float64,2}}
end    

In [26]:
resVar = ResVar(R0,Dict())

ResVar(3x3 Array{Float64,2}:
 1.0  0.5  0.5
 0.5  2.0  0.5
 0.5  0.5  4.0,Dict{BitArray{1},Array{Float64,2}}())

In [43]:
function getRi(resVar::ResVar,sel::BitArray{1})
    if haskey(resVar.RiDict,sel)
        return resVar.RiDict[sel]
    end
    n = size(resVar.R0,1)
    RZ = zeros(n,n)
    RZ[sel,sel] = inv(resVar.R0[sel,sel])
    resVar.RiDict[sel] = RZ
    return RZ
end

getRi (generic function with 1 method)

In [28]:
tstMsng

4x3 BitArray{2}:
 true   true   true
 true  false   true
 true   true  false
 true   true   true

In [29]:
reshape(tstMsng[1,:],3)

3-element BitArray{1}:
 true
 true
 true

In [30]:
sel = reshape(tstMsng[1,:],3)
getRi(resVar,sel)

3x3 Array{Float64,2}:
  1.19231   -0.269231   -0.115385 
 -0.269231   0.576923   -0.0384615
 -0.115385  -0.0384615   0.269231 

In [31]:
typeof(sel)

BitArray{1} (constructor with 1 method)

In [32]:
sel = reshape(tstMsng[2,:],3)
getRi(resVar,sel)

3x3 Array{Float64,2}:
  1.06667   0.0  -0.133333
  0.0       0.0   0.0     
 -0.133333  0.0   0.266667

In [33]:
sel = reshape(tstMsng[3,:],3)
getRi(resVar,sel)

3x3 Array{Float64,2}:
  1.14286   -0.285714  0.0
 -0.285714   0.571429  0.0
  0.0        0.0       0.0

In [34]:
sel = reshape(tstMsng[4,:],3)
getRi(resVar,sel)

3x3 Array{Float64,2}:
  1.19231   -0.269231   -0.115385 
 -0.269231   0.576923   -0.0384615
 -0.115385  -0.0384615   0.269231 

In [35]:
resVar

ResVar(3x3 Array{Float64,2}:
 1.0  0.5  0.5
 0.5  2.0  0.5
 0.5  0.5  4.0,[Bool[true,false,true]=>3x3 Array{Float64,2}:
  1.06667   0.0  -0.133333
  0.0       0.0   0.0     
 -0.133333  0.0   0.266667,Bool[true,true,false]=>3x3 Array{Float64,2}:
  1.14286   -0.285714  0.0
 -0.285714   0.571429  0.0
  0.0        0.0       0.0,Bool[true,true,true]=>3x3 Array{Float64,2}:
  1.19231   -0.269231   -0.115385 
 -0.269231   0.576923   -0.0384615
 -0.115385  -0.0384615   0.269231 ])

In [36]:
function GaussSeidel(A,x,b;tol=0.000001)
    n = size(x,1)
    for i=1:n
        x[i] = ((b[i] - A[i,:]*x)/A[i,i])[1,1] + x[i]
    end
    diff = sum((A*x-b).^2)
    iter = 0
    while ((diff/n > tol) & (iter<1000))
        iter += 1
        for i=1:n
            x[i] = ((b[i] - A[i,:]*x)/A[i,i])[1,1] + x[i]
        end
        diff = sum((A*x-b).^2)
        println(iter," ",diff/n)
    end
    return x
end

function Jacobi(A,x,b,p;tol=0.000001)
    D       = diag(A)
    res     = A*x
    resid   = b-res
    tempSol = resid./D
    diff    = sum(resid.^2)
    n    = size(A,1)
    iter = 0
    while ((diff/n > tol) & (iter<1000))
        iter += 1
        x = p*tempSol + (1-p)*x
        res     = A*x
        resid   = b-res
        tempSol = resid./D + x
        diff    = sum(resid.^2)
        println(iter," ",diff/n)
    end
    return x
end


type TermStrVal
    str::String
    value::Float64
end

type TermLvlVal
    level::String
    value::Float64
end

type ModelTerm 
    iModel::Int64
    trmStr::String
    nFactors::Int64
    factors::Array{Symbol,1}
    str::Array{String,1}                    # used to store the data for this term as strings
    val::Array{Float64,1}
    startPos::Int64                         # start pos in HMME
    nLevels::Int64                           
    X::SparseMatrixCSC{Float64,Int64}
    names::Array{Any,1}
end
type MME
    modelVec::Array{String,1}
    modelTerms::Array{ModelTerm,1}
    modelTermDict::Dict{String,ModelTerm}
    lhsVec::Array{Symbol,1}
    covVec::Array{Symbol,1}
    pedTrmVec::Array{String,1}
    mmeLhs
    mmeRhs
    ped
    Gi::Array{Float64,2}
    R::Array{Float64,2}
    Ai
    mmePos::Int64
end

function mkDict(a)
    aUnique = unique(a)
    d = Dict()
    names = Array(Any,size(aUnique,1))
    for (i,s) in enumerate(aUnique)
        names[i] = s
        d[s] = i
    end
    return d,names
end

function getTerm(trmStr,m)
    trm = ModelTerm(m,string(m)*":"*trmStr,0,[],[],[],0,0,spzeros(0,0),[])
    factorVec = split(trmStr,"*")
    trm.nFactors = length(factorVec)
    trm.factors = [symbol(strip(f)) for f in factorVec]
    return trm
end

function initMME(models::String,R::Array{Float64,2})
    # returns an MME object for muilding the mme corresponding 
    # to the input string
    if models==""
        println("modelEquation is empty\n")
        return
    end
    modelVec = split(models,[';','\n'],false)
    nModels  = size(modelVec,1)
    lhsVec   = Symbol[]
    modelTerms = ModelTerm[]
    dict = Dict{String,ModelTerm}()
    for (m,model) = enumerate(modelVec)
        lhsRhs = split(model,"=")
        lhsVec = [lhsVec,symbol(strip(lhsRhs[1]))]
        rhs = strip(lhsRhs[2])
        rhsVec = split(rhs,"+")    
        mTrms = [getTerm(strip(trmStr),m) for trmStr in rhsVec]
        modelTerms = [modelTerms, mTrms]
        for (i,trm) = enumerate(modelTerms) 
            dict[trm.trmStr] = modelTerms[i]
        end 
    end
    return MME(modelVec,modelTerms,dict,lhsVec,[],[],0,0,0,Array(Float64,1,1),R,0,1)
end 

function getData(trm::ModelTerm,df::DataFrame,mme::MME)
    nObs = size(df,1)
    trm.str = Array(String,nObs)
    trm.val = Array(Float64,nObs)
    if(trm.factors[1] == :intercept)                     # from Melanie's HW
        str = fill(string(trm.factors[1]),nObs)
        val = fill(1.0,nObs)
    else
        myDf = df[trm.factors]
        if trm.factors[1] in mme.covVec
            str = fill(string(trm.factors[1]),nObs)
            val = df[trm.factors[1]]
        else
            str = [string(i) for i in df[trm.factors[1]]]
            val = fill(1.0,nObs)
        end
        for i=2:trm.nFactors
            if trm.factors[i] in mme.covVec
                str = str .* fill("*"*string(trm.factors[i]),nObs)
                val = val .* df[trm.factors[i]]
            else
                str = str .* fill("*",nObs) .* [string(j) for j in df[trm.factors[i]]]
                val = val .* fill(1.0,nObs)
            end
        end
    end
    trm.str = str
    trm.val = val
end

getFactor1(str) = [strip(i) for i in split(str,"*")][1]

function getX(trm,mme::MME)
    pedSize = 0
    nObs  = size(trm.str,1)
    if trm.trmStr in mme.pedTrmVec
        trm.names   = PedModule.getIDs(mme.ped)
        trm.nLevels = length(mme.ped.idMap)
        xj = int([mme.ped.idMap[getFactor1(i)].seqID for i in trm.str])
    else
        dict,trm.names  = mkDict(trm.str)
        trm.nLevels     = length(dict)
        xj    = int([dict[i] for i in trm.str])
    end
    xi    = (trm.iModel-1)*nObs + [1:nObs]
    xv    = trm.val
    if mme.ped!=0
        pedSize = length(mme.ped.idMap)
        if trm.trmStr in mme.pedTrmVec
            # This is to ensure the X matrix for 
            # additive effect has the correct number of columns
            ii = 1         # adding a zero to
            jj = pedSize   # the last column in row 1
            vv = [0.0]
            xi = [xi,ii]
            xj = [xj,jj]
            xv = [xv,vv]
        end
    end 
    #make sure X has nObs*nModels rows
    nModels = size(mme.lhsVec,1)
    xi = [xi,1,nObs*nModels]
    xj = [xj,1,1]
    xv = [xv,0,0]
    trm.X = sparse(xi,xj,xv)
    trm.startPos = mme.mmePos
    mme.mmePos  += trm.nLevels
end

function mkRi(mme::MME,df::DataFrame)
    resVar = ResVar(mme.R,Dict())
    tstMsng = !isna(df[mme.lhsVec[1]])
    for i=2:size(mme.lhsVec,1)
        tstMsng = [tstMsng !isna(df[mme.lhsVec[i]])]
    end
    n    = size(tstMsng,2)
    nObs = size(tstMsng,1)
    ii = Array(Int64,nObs*n^2)
    jj = Array(Int64,nObs*n^2)
    vv = Array(Float64,nObs*n^2)
    pos = 1
    for i=1:size(tstMsng,1)
        sel = reshape(tstMsng[i,:],n)
        Ri  = getRi(resVar,sel)
        for ti=1:n
            tii = (ti-1)*nObs + i
            for tj=1:n
                tjj = (tj-1)*nObs + i
                ii[pos] = tii
                jj[pos] = tjj
                vv[pos] = Ri[ti,tj]
                pos += 1
            end
        end         
    end
    return sparse(ii,jj,vv)
end

function getMME(mme::MME, df::DataFrame)
    mme.mmePos = 1
    for trm in mme.modelTerms
        getData(trm,df,mme)
        getX(trm,mme)
    end
    n   = size(mme.modelTerms,1)
    trm = mme.modelTerms[1]
    X   = trm.X
    for i=2:n
        trm = mme.modelTerms[i]
        X = [X trm.X]
    end
    y = convert(Array,df[mme.lhsVec[1]],0.0)
    for i=2:size(mme.lhsVec,1)
        y    = [y, convert(Array,df[mme.lhsVec[i]],0.0)] 
    end
    N  = size(y,1)
    ii = 1:N
    jj = fill(1,N)
    vv = y
    ySparse = sparse(ii,jj,vv)
    nObs = size(df,1)
    Ri = mkRi(mme,df)
    mme.mmeLhs = X'Ri*X
    mme.mmeRhs = X'Ri*ySparse
    if mme.ped != 0
        ii,jj,vv = PedModule.HAi(mme.ped)
        HAi = sparse(ii,jj,vv)
        mme.Ai = HAi'HAi
        addA(mme::MME)
    end   
end

function getNames(mme)
    names = Array(String,0)
    for trm in mme.modelTerms
        for name in trm.names
            push!(names,trm.trmStr*": "*name)
        end
    end
    return names
end  

function covList(mme::MME, covStr::String)
    covVec = split(covStr," ",false) 
    mme.covVec = [symbol(i) for i in covVec]
    nothing
end

function getSolJ(mme::MME, df::DataFrame)
    if size(mme.mmeRhs)==() 
        getMME(mme,df)
    end
    p = size(mme.mmeRhs,1)
    return [getNames(mme) Jacobi(mme.mmeLhs,fill(0.0,p),mme.mmeRhs,0.3,tol=0.000001)]
end

function getSolG(mme::MME, df::DataFrame)
    if size(mme.mmeRhs)==() 
        getMME(mme,df)
    end
    p = size(mme.mmeRhs,1)
    return [getNames(mme) GaussSeidel(mme.mmeLhs,fill(0.0,p),mme.mmeRhs,tol=0.000001)]
end

function setAsRandom(mme::MME,randomStr::String,ped::PedModule.Pedigree, G::Array{Float64,2})
    pedTrmVec = split(randomStr," ",false)
    res = []
    for trm in pedTrmVec
        for (m,model) = enumerate(mme.modelVec)
            strVec  = split(model,['=','+'])
            strpVec = [strip(i) for i in strVec]
            if trm in strpVec
                res = [res,string(m)*":"*trm]
            end
        end
    end
    mme.pedTrmVec = res
    mme.ped = ped
    mme.Gi = inv(G)
    nothing
end

function addA(mme::MME)
    pedTrmVec = mme.pedTrmVec
    for (i,trmi) = enumerate(pedTrmVec)
        pedTrmi  = mme.modelTermDict[trmi]
        startPosi  = pedTrmi.startPos
        endPosi    = startPosi + pedTrmi.nLevels - 1
        for (j,trmj) = enumerate(pedTrmVec)
            pedTrmj  = mme.modelTermDict[trmj]
            startPosj  = pedTrmj.startPos
            endPosj    = startPosj + pedTrmj.nLevels - 1  
            mme.mmeLhs[startPosi:endPosi,startPosj:endPosj] = 
            mme.mmeLhs[startPosi:endPosi,startPosj:endPosj] + mme.Ai*mme.Gi[i,j] 
        end
    end
end

addA (generic function with 1 method)

### Multiple Trait Animal Model 

In [37]:
models = "y1 = intercept + trt;
          y2 = intercept + trt;
          y3 = intercept + trt"
mme = initMME(models,R0);

In [38]:
df[mme.lhsVec]

4x3 DataFrame
| Row | y1  | y2  | y3  |
|-----|-----|-----|-----|
| 1   | 1.0 | 2.0 | 1.2 |
| 2   | 1.1 | NA  | 3.1 |
| 3   | 0.9 | 1.9 | NA  |
| 4   | 1.2 | 1.7 | 1.9 |

In [39]:
getMME(mme,df);

In [40]:
full(mme.mmeLhs)

9x9 Array{Float64,2}:
  4.59414    2.25897    2.33516   …  -0.364103   -0.248718   -0.115385 
  2.25897    2.25897    0.0          -0.248718   -0.248718    0.0      
  2.33516    0.0        2.33516      -0.115385    0.0        -0.115385 
 -0.824176  -0.269231  -0.554945     -0.0769231  -0.0384615  -0.0384615
 -0.269231  -0.269231   0.0          -0.0384615  -0.0384615   0.0      
 -0.554945   0.0       -0.554945  …  -0.0384615   0.0        -0.0384615
 -0.364103  -0.248718  -0.115385      0.805128    0.535897    0.269231 
 -0.248718  -0.248718   0.0           0.535897    0.535897    0.0      
 -0.115385   0.0       -0.115385      0.269231    0.0         0.269231 

In [49]:
sel = [true, true, false]

models = "y1 =  trt;
          y2 =  trt;"
mme = initMME(models,R0[sel,sel]);

In [50]:
getMME(mme,df)

In [52]:
round(full(mme.mmeLhs),3)

4x4 Array{Float64,2}:
  2.143   0.0    -0.286   0.0  
  0.0     2.286   0.0    -0.571
 -0.286   0.0     0.571   0.0  
  0.0    -0.571   0.0     1.143